spring.application.name=demo-receiver
spring.cloud.azure.credential.managed-identity-enabled=${SPRING_CLOUD_AZURE_CREDENTIAL_MANAGED_IDENTITY_ENABLED:false}
spring.cloud.azure.credential.client-id=${AZURE_CLIENT_ID:}

spring.cloud.azure.servicebus.namespace=${SPRING_CLOUD_AZURE_SERVICEBUS_NAMESPACE:}
spring.cloud.azure.servicebus.entity-name=${SPRING_CLOUD_AZURE_SERVICEBUS_ENTITY_NAME:}
spring.cloud.azure.servicebus.entity-type=queue

spring.cloud.azure.eventhubs.namespace=${SPRING_CLOUD_AZURE_EVENTHUBS_NAMESPACE:}
spring.cloud.azure.eventhubs.event-hub-name=${SPRING_CLOUD_AZURE_EVENTHUBS_EVENT_HUB_NAME:}
spring.cloud.azure.eventhubs.processor.checkpoint-store.account-name=${SPRING_CLOUD_AZURE_EVENTHUBS_PROCESSOR_CHECKPOINT_STORE_ACCOUNT_NAME:}
spring.cloud.azure.eventhubs.processor.checkpoint-store.container-name=${SPRING_CLOUD_AZURE_EVENTHUBS_PROCESSOR_CHECKPOINT_STORE_CONTAINER_NAME:}
spring.cloud.azure.eventhubs.processor.checkpoint-store.credential.managed-identity-enabled=true
spring.cloud.azure.eventhubs.processor.consumer-group=${SPRING_CLOUD_AZURE_EVENTHUBS_PROCESSOR_CONSUMER_GROUP:}

spring.cloud.azure.eventhubs.processor.initial-partition-event-position.0.offset=-1
spring.cloud.azure.eventhubs.processor.initial-partition-event-position.0.inclusive=true
spring.cloud.azure.eventhubs.processor.initial-partition-event-position.1.offset=-1
spring.cloud.azure.eventhubs.processor.initial-partition-event-position.1.inclusive=true

spring.cloud.azure.cosmos.endpoint=${SPRING_CLOUD_AZURE_COSMOS_ENDPOINT:}
spring.cloud.azure.cosmos.database=${SPRING_CLOUD_AZURE_COSMOS_DATABASE:}
