spring.application.name=demo-eventhub-receiver

spring.cloud.azure.eventhubs.namespace=huygnguyenehubns
spring.cloud.azure.eventhubs.event-hub-name=myeventhub
spring.cloud.azure.eventhubs.processor.checkpoint-store.account-name=demoehubsa
spring.cloud.azure.eventhubs.processor.checkpoint-store.container-name=demoehubcontainer
spring.cloud.azure.eventhubs.processor.consumer-group=$Default

spring.cloud.azure.cosmos.endpoint=https://demo-huygnguyen-cosmos-db.documents.azure.com:443/
spring.cloud.azure.cosmos.database=app-db
spring.cloud.azure.cosmos.populate-query-metrics=true
