spring.application.name=demo-servicebus-receiver
spring.cloud.azure.credential.managed-identity-enabled=${SPRING_CLOUD_AZURE_CREDENTIAL_MANAGED_IDENTITY_ENABLED:false}
spring.cloud.azure.credential.client-id=${AZURE_CLIENT_ID:}
spring.cloud.azure.servicebus.namespace=${SPRING_CLOUD_AZURE_SERVICEBUS_NAMESPACE:}
spring.cloud.azure.servicebus.entity-name=${SPRING_CLOUD_AZURE_SERVICEBUS_ENTITY_NAME:}
spring.cloud.azure.servicebus.entity-type=queue
spring.cloud.azure.cosmos.endpoint=${SPRING_CLOUD_AZURE_COSMOS_ENDPOINT:}
spring.cloud.azure.cosmos.database=${SPRING_CLOUD_AZURE_COSMOS_DATABASE:}
