name: Deploy to Azure Container Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build jar file
        run: mvn -B clean package

      - name: Login to Azure
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        run: |
          az acr build \
            --registry crevhreceiverdev \
            --image evh-receiver:${{ github.sha }} \
            --image evh-receiver:latest \
            .

  deploy:
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    permissions:
      id-token: write
      contents: none
    steps:
      - name: Login to Azure
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name ca-evh-receiver-dev \
            --resource-group rg-evh-receiver-dev \
            --image crevhreceiverdev.azurecr.io/evh-receiver:${{ github.sha }}
